// Scenescape_front/src/App.vue
<script setup>
import { RouterView } from "vue-router";
import VHeader from "@/components/VHeader.vue";
import VFooter from "@/components/VFooter.vue";
import VChatBotButton from "./components/VChatBot/VChatBotButton.vue";
</script>

<template>
  <div class="min-w-screen max-w-[120rem] min-h-screen mx-auto flex flex-col">
    <header>
      <VHeader />
    </header>

    <main class="flex-grow">
      <RouterView />
    </main>

    <!-- <footer>
      <VFooter />
    </footer> -->

    <VChatBotButton />
  </div>
</template>

<style scoped></style>

// Scenescape_front(React)/src/App.jsx
import { Routes, Route } from "react-router-dom";

import Header from "./components/Header";
import Footer from "./components/Footer";
import Home from "./pages/Home";
import Login from "./pages/Login";
import LoginForm from "./components/LoginForm";
import FindPasswordForm from "./components/FindPasswordForm";
import SignUp from "./pages/SignUp";
import MyPage from "./pages/MyPage";
import Plan from "./pages/Plan";
import Board from "./pages/Board";
import NotFound from "./pages/NotFound";

const Layout = ({ header, main, footer }) => {
  return (
    <div className="flex flex-col max-w-[120rem] min-h-screen mx-auto">
      <header>{header}</header>
      <main className="flex-1">{main}</main>
      <footer>{footer}</footer>
    </div>
  );
};

const App = () => {
  return (
    <Routes>
      <Route
        path="/"
        element={
          <Layout
            header={<Header />}
            main={<Home />}
            footer={<Footer />}
          />
        }
      />
      <Route
        path="/login"
        element={
          <Layout
            header={<Header />}
            main={<Login />} // Login 페이지를 렌더링
            footer={<Footer />}
          />
        }
      >
        <Route
          index
          element={<LoginForm />}
        />
        <Route
          path="find-password"
          element={<FindPasswordForm />}
        />
      </Route>
      <Route
        path="/signup"
        element={
          <Layout
            header={<Header />}
            main={<SignUp />}
            footer={<Footer />}
          />
        }
      />
      <Route
        path="/mypage"
        element={
          <Layout
            header={<Header />}
            main={<MyPage />}
            footer={<Footer />}
          />
        }
      />
      <Route
        path="/plan"
        element={
          <Layout
            header={<Header />}
            main={<Plan />}
          />
        }
      />
      <Route
        path="/board"
        element={
          <Layout
            header={<Header />}
            main={<Board />}
            footer={<Footer />}
          />
        }
      />
      <Route
        path="*"
        element={<NotFound />}
      />
    </Routes>
  );
};

export default App;
